const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
const Quote = require("./quote.model");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.quotes = new Quote();
module.exports = db;